"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { SignOutButton } from "@/components/AuthButtons";

type Hotel = { id: number; canonicalName: string; locality: string; region: string; isArchived: boolean };
type Row = { id: number; invitedNames: string[]; groupLabel: string | null; attending: boolean | null; outOfTown: boolean | null; partySize: number | null; partyMembers: string[]; eligible: boolean; lodging: { lodgingType: string; localArea: string | null } | null; hotel: Hotel | null; legs: Array<{ direction: string; mode: string; scheduledAt: string | null; travelDate: string | null; timePeriod: string | null; airlineCode: string | null; flightNumber: string | null }> };

const ink = "var(--ink-warm)"; const muted = "var(--ink-muted)"; const border = "1px solid rgba(26,22,19,.12)";

export default function AdminStayPortal() {
  const [rows, setRows] = useState<Row[]>([]); const [hotels, setHotels] = useState<Hotel[]>([]); const [filter, setFilter] = useState("all"); const [loading, setLoading] = useState(true); const [mergeTargets, setMergeTargets] = useState<Record<number, string>>({}); const [actionError, setActionError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setActionError(null); try { const res = await fetch("/api/admin/stay"); const data = await res.json().catch(() => null); if (!res.ok) { setActionError(data?.error || "Could not load stay plans."); return; } setRows(data.rows); setHotels(data.hotels); } catch { setActionError("Could not load stay plans. Check your connection and try again."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const shown = rows.filter((row) => filter === "all" ? true : filter === "incomplete" ? !row.lodging || row.legs.length < 2 : filter === "inactive" ? !row.eligible : row.hotel?.id === Number(filter));
  function exportCsv() { setActionError(null); try { const values = [["Group", "Label", "Eligible", "Travelers", "Lodging", "Hotel / area", "Arrival", "Departure"], ...shown.map((row) => [row.invitedNames.join("; "), row.groupLabel ?? "", row.eligible ? "Yes" : "No", String(row.partySize ?? 0), row.lodging?.lodgingType ?? "", row.hotel ? `${row.hotel.canonicalName} — ${row.hotel.locality}, ${row.hotel.region}` : row.lodging?.localArea ?? "", legSummary(row, "arrival"), legSummary(row, "departure")])]; const csv = values.map((cols) => cols.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = "stay-plans.csv"; a.click(); URL.revokeObjectURL(url); } catch { setActionError("Could not create the CSV export."); } }
  async function toggleHotel(hotel: Hotel) { setActionError(null); try { const res = await fetch(`/api/admin/stay/hotels/${hotel.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isArchived: !hotel.isArchived }) }); const data = await res.json().catch(() => null); if (!res.ok) { setActionError(data?.error || `Could not ${hotel.isArchived ? "restore" : "archive"} that hotel.`); return; } await load(); } catch { setActionError("Could not update that hotel. Check your connection and try again."); } }
  async function mergeHotel(hotel: Hotel) { const mergeIntoId = Number(mergeTargets[hotel.id]); if (!mergeIntoId) return; setActionError(null); try { const res = await fetch(`/api/admin/stay/hotels/${hotel.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "merge", mergeIntoId }) }); const data = await res.json().catch(() => null); if (!res.ok) { setActionError(data?.error || "Could not merge those hotels."); return; } await load(); } catch { setActionError("Could not merge those hotels. Check your connection and try again."); } }
  return <main style={{ minHeight: "100vh", background: "var(--paper)", color: ink, padding: "2rem 1rem", fontFamily: "var(--font-pt), Georgia, serif" }}><div style={{ maxWidth: "78rem", margin: "0 auto" }}>
    <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "1rem", flexWrap: "wrap", marginBottom: "1.5rem" }}><div><h1 style={{ margin: 0, fontFamily: "var(--font-gilda), serif", fontWeight: 400 }}>Stay Plans <span style={{ color: "var(--star)" }}>★</span></h1><p style={{ margin: ".3rem 0 0", color: muted, fontSize: ".82rem" }}>Lodging and travel details for eligible out-of-town guests.</p></div><nav style={{ display: "flex", gap: "1rem", alignItems: "center", fontSize: ".82rem" }}><Link href="/admin" style={{ color: muted }}>Guest Admin</Link><Link href="/analytics" style={{ color: muted }}>Analytics</Link><SignOutButton /></nav></header>
    <div style={{ display: "flex", gap: ".6rem", flexWrap: "wrap", alignItems: "center", marginBottom: "1rem" }}><select value={filter} onChange={(e) => setFilter(e.target.value)} style={{ border, borderRadius: "999px", padding: ".5rem .8rem", background: "white", color: ink }}><option value="all">All plans</option><option value="incomplete">Incomplete</option><option value="inactive">No longer eligible</option>{hotels.filter((hotel) => !hotel.isArchived).map((hotel) => <option key={hotel.id} value={hotel.id}>{hotel.canonicalName}</option>)}</select><button onClick={exportCsv} style={{ border, borderRadius: "999px", padding: ".5rem .9rem", background: ink, color: "white" }}>Export CSV</button><span style={{ color: muted, fontSize: ".8rem" }}>{shown.length} groups · {shown.reduce((sum, row) => sum + (row.partySize ?? 0), 0)} current travelers</span></div>
    {actionError && <p role="alert" style={{ margin: "0 0 1rem", borderRadius: ".6rem", background: "rgba(155,28,28,.08)", color: "#9b1c1c", padding: ".7rem .85rem", fontSize: ".8rem" }}>{actionError}</p>}
    <section style={{ overflowX: "auto", border, borderRadius: ".8rem" }}><table style={{ borderCollapse: "collapse", width: "100%", minWidth: "60rem", fontSize: ".8rem" }}><thead style={{ background: "#f5f3ef", color: muted }}><tr>{["Group", "Travelers", "Stay", "Arrival", "Departure", "Status", ""].map((title) => <th key={title} style={{ textAlign: "left", padding: ".65rem .8rem", fontWeight: 500 }}>{title}</th>)}</tr></thead><tbody>{shown.map((row) => <tr key={row.id} style={{ borderTop: border }}><td style={{ padding: ".7rem .8rem" }}><strong>{row.invitedNames.join(", ")}</strong><div style={{ color: muted }}>{row.groupLabel}</div></td><td style={{ padding: ".7rem .8rem" }}>{row.partySize ?? 0}<div style={{ color: muted }}>{row.partyMembers.join(", ")}</div></td><td style={{ padding: ".7rem .8rem" }}>{staySummary(row)}</td><td style={{ padding: ".7rem .8rem" }}>{legSummary(row, "arrival")}</td><td style={{ padding: ".7rem .8rem" }}>{legSummary(row, "departure")}</td><td style={{ padding: ".7rem .8rem", color: row.eligible ? "#287047" : "#9b1c1c" }}>{row.eligible ? (row.lodging && row.legs.length === 2 ? "Complete" : "Incomplete") : "Inactive"}</td><td style={{ padding: ".7rem .8rem" }}>{row.eligible && <Link href={`/admin/stay/${row.id}`} style={{ color: ink }}>Edit</Link>}</td></tr>)}</tbody></table>{loading && <p style={{ padding: "1rem", color: muted }}>Loading…</p>}</section>
    <section style={{ marginTop: "1.5rem" }}><h2 style={{ fontFamily: "var(--font-gilda), serif", fontWeight: 400 }}>Hotel catalog</h2><div style={{ display: "grid", gap: ".45rem" }}>{hotels.map((hotel) => <div key={hotel.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: ".65rem", border, borderRadius: ".65rem", padding: ".65rem .8rem", opacity: hotel.isArchived ? .55 : 1 }}><span>{hotel.canonicalName} — {hotel.locality}, {hotel.region}</span><span style={{ display: "flex", gap: ".4rem", alignItems: "center" }}>{!hotel.isArchived && <><select aria-label={`Merge ${hotel.canonicalName} into`} value={mergeTargets[hotel.id] ?? ""} onChange={(e) => setMergeTargets((current) => ({ ...current, [hotel.id]: e.target.value }))} style={{ maxWidth: "12rem", border, borderRadius: ".4rem", padding: ".3rem" }}><option value="">Merge into…</option>{hotels.filter((item) => !item.isArchived && item.id !== hotel.id).map((item) => <option key={item.id} value={item.id}>{item.canonicalName}</option>)}</select><button disabled={!mergeTargets[hotel.id]} onClick={() => mergeHotel(hotel)} style={{ border: 0, background: "none", color: muted, textDecoration: "underline" }}>Merge</button></>}<button onClick={() => toggleHotel(hotel)} style={{ border: 0, background: "none", color: muted, textDecoration: "underline" }}>{hotel.isArchived ? "Restore" : "Archive"}</button></span></div>)}</div></section>
  </div></main>;
}

function staySummary(row: Row) { if (!row.lodging) return "—"; if (row.lodging.lodgingType === "hotel") return row.hotel ? `${row.hotel.canonicalName} — ${row.hotel.locality}` : "Archived hotel"; if (row.lodging.lodgingType === "friend_or_family") return `Friends/family — ${row.lodging.localArea}`; return "Undecided"; }
function legSummary(row: Row, direction: string) { const leg = row.legs.find((item) => item.direction === direction); if (!leg) return "—"; if (leg.mode === "drive") return `Drive · ${leg.travelDate} ${leg.timePeriod}`; if (leg.mode === "flight") return `Flight · ${leg.airlineCode}${leg.flightNumber ? ` ${leg.flightNumber}` : ""} · ${formatDate(leg.scheduledAt)}`; if (leg.mode === "bus") return `Bus · ${formatDate(leg.scheduledAt)}`; return leg.mode === "undecided" ? "Undecided" : "Other"; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : ""; }
